"""added car model

Revision ID: c1ca3c0ace3c
Revises: 8b7b643cb01c
Create Date: 2023-05-29 00:46:17.907653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ca3c0ace3c'
down_revision = '8b7b643cb01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Date(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id', 'color')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
